# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_config.json
data_model_schema: solitaire_ue
cohorted_daily_kpis_days: [0, 1, 2, 3, 4, 5, 6, 7, 14, 21, 28, 30, 40, 50, 60, 90, 120, 180, 270, 360]
active_days: 90
